apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-classifier
  template:
    metadata:
      labels:
        app: reddit-classifier
    spec:
      containers:
        - name: reddit-classifier
          image: gcr.io/reddit-classifier-ml/reddit-classifier:v3
          ports:
            - containerPort: 8080
