apiVersion: v1
kind: Service
metadata:
  name: reddit-classifier-service
spec:
  type: LoadBalancer
  selector:
    app: reddit-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
